import Link from "next/link";
import { ArrowRight, ShieldCheck, MapPin, CalendarDays, Check, Phone, Mail, MessageSquareText } from "lucide-react";
import { services, site } from "@/lib/site";
import { SectionHeading } from "@/components/section-heading";

export default function Home() { return <>
  <section className="hero">
    <div className="hero-wash"/>
    <div className="container hero-grid">
      <div className="hero-copy">
        <h1>Your life is unique. <em>Your coverage should be too.</em></h1><p>I take time to understand what matters to you, then work to find policies suited to your needs, priorities and budget.</p>
  <div className="hero-location"><MapPin size={16}/> Proud to serve British Columbia and Manitoba</div></div><div className="hero-contact-actions"><a className="button hero-action-primary" href={`tel:${site.phoneLink}`}><Phone size={19}/> <span>Call now<small>{site.phone}</small></span><ArrowRight size={18}/></a><a className="button hero-action-secondary" href={`mailto:${site.email}`}><Mail size={19}/> <span>Email me<small>{site.email}</small></span><ArrowRight size={18}/></a><Link className="button hero-action-tertiary" href="/contact#contact-form"><MessageSquareText size={19}/> Get a free quote <ArrowRight size={18}/></Link></div></div></section>
  <section className="trust-strip"><div className="container trust-grid"><div><ShieldCheck/><span><strong>Personal guidance</strong><small>Start with your questions</small></span></div><div><MapPin/><span><strong>BC & Manitoba</strong><small>Serving clients remotely</small></span></div><div><CalendarDays/><span><strong>Flexible conversations</strong><small>Connect by phone or email</small></span></div></div></section>
  <section className="section"><div className="container"><SectionHeading eyebrow="What I can help with" title="Advice shaped around you" text="From protecting your family to planning ahead, we’ll focus on what suits your life and priorities."/><div className="service-grid">{services.map((service, index) => <Link className="service-card" href="/services" key={service.title}><span className="card-index">0{index + 1}</span><h3>{service.title}</h3><p>{service.text}</p><span className="card-arrow">Explore this area <ArrowRight size={16}/></span></Link>)}</div><div className="section-action"><Link className="button button-outline" href="/services">All services <ArrowRight size={16}/></Link></div></div></section>
  <section className="section section-tint"><div className="container two-col"><div><span className="eyebrow">My promise to you</span><h2>Clear answers. Thoughtful choices. No rush.</h2></div><div><p className="lead">I’ll listen first, then work hard to find the strongest fit among the options available to you—and explain the trade-offs in plain language.</p><ul className="check-list"><li><Check/> Your needs and priorities lead the way</li><li><Check/> You’ll know what you’re choosing and why</li><li><Check/> You decide what feels right for you</li></ul><Link href="/about" className="text-link">Learn about my approach <ArrowRight size={16}/></Link></div></div></section>
  <section className="section cta-section"><div className="container cta-card"><div><span className="eyebrow light">A good place to start</span><h2>See what options may fit.</h2><p>Tell me what you need, and I’ll follow up personally. There’s no charge to request a quote.</p></div><div className="cta-actions"><Link className="button button-light" href="/contact#contact-form">Get a free quote <ArrowRight size={16}/></Link><a href={`tel:${site.phoneLink}`} className="button button-ghost">Call Kamaljit</a></div></div></section>
</> }
