"use client";
import { FormEvent, useState } from "react";

export function ContactForm() {
  const [status, setStatus] = useState("");
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = e.currentTarget; setStatus("Sending…"); const data = Object.fromEntries(new FormData(form)); try { const r = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const result = await r.json(); setStatus(result.message); if (r.ok) form.reset(); } catch { setStatus("We couldn’t send your message. Please call or email Kamaljit directly."); } }
  return <form className="form-card" onSubmit={submit}><h3>Request a free quote</h3><p>Tell me what you’re looking for and I’ll follow up to learn more. There’s no charge to request a quote.</p><label>Your name<input name="name" required maxLength={100} autoComplete="name"/></label><label>Email address<input type="email" name="email" required maxLength={254} autoComplete="email"/>
  </label><label>Phone number<input type="tel" name="phone" required maxLength={24} autoComplete="tel"/></label><label>What would you like a quote for? <span className="field-optional">(optional)</span><select name="interest" defaultValue=""><option value="">Choose a service</option>{quoteInterests.map((item) => <option value={item} key={item}>{item}</option>)}</select></label><label>Anything else you’d like me to know?<textarea name="message" required maxLength={1000} rows={4} placeholder="Please keep health, financial, identity and policy details out of this form."/></label><label className="consent"><input type="checkbox" name="consent" required/><span>I agree that Kamaljit may use my contact details to respond to this request. <a href="/privacy">Privacy notice</a></span></label><button className="button button-primary" type="submit" disabled={status === "Sending…"}>{status === "Sending…" ? "Sending…" : "Request a free quote"}</button><small className="form-disclaimer">A quote is an estimate for discussion and does not issue or bind insurance coverage.</small>{status && <p role="status" className="form-status">{status}</p>}</form>
}

const quoteInterests = ["Life insurance", "Mortgage insurance", "Disability insurance", "Critical illness insurance", "Super Visa insurance", "Visitor insurance", "Travel insurance", "International student insurance", "Health plans", "Dental plans", "RESP", "RRSP", "TFSA"];
